### ISSUE TITLE
Getting SD card error 2

### ISSUE THREAD

**Issue by AlefCS** [greiman/Fat16#2]
Hi,

I tried to run the example **fat16ls** but without success. The program returned a SD card error 2. I use a 16 GB SD card, but the only partition in it was a 1GB FAT16 primary partition. It shouldn't work?

**Comment by greiman** [comment]
A 16GB card is SDHC so will not work since it has a different command protocol.  Only Standard-Capacity (SDSC) cards 2GB and smaller work.

See [this](https://en.wikipedia.org/wiki/Secure_Digital).
