### ISSUE TITLE
can block size be reduced to say 128 bytes?

### ISSUE THREAD

**Issue by steveh2112** [greiman/Fat16#5]
i have a data logger app that only every writes in 80 byte blocks, once a second, i was wandering if its possible to reduce the size of this 
union cache16_t {
          /** Used to access cached file data blocks. */
  uint8_t data[512];
to something like 128?

**Comment by greiman** [comment]
The size of an SD sector is 512 bytes so the size must be 512 since it is necessary to read or write an entire sector.
